name: fypnewproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: any
  firebase_auth: any
  provider: any
  firebase_database: any
  google_sign_in: any
  image_picker: any
  font_awesome_flutter: any
  shared_preferences: any
  firebase_storage: any
  cloud_firestore: any
  file_picker: any
  path: any
  google_maps_flutter: any
  firebase_messaging: any
  fluttertoast: any
  intl: any
  flutter_local_notifications: any
  photo_view: any
  country_code_picker: any
  url_launcher: any
  uuid: any
  cached_network_image: any
  firebase_analytics: any
  firebase_crashlytics: any
  open_filex: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# ✅ Naya sahi config (flutter_launcher_icons use karna hai, na ke flutter_icons)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - "assets/logo.png"
